In [13]:
import requests, time
import pandas as pd

In [4]:
your_key = open('your_key.txt', 'r').read()

In [5]:
def articles_df(init, finit):
    ''' retorna um dataframe com informações a respeito de artigos 
        publicados na NYT durante todo o período compreendido entre
        os anos init e finit
        
        ex. init 2020 e finit 2022, retorna dataframe de 2020, 2021 e 2022'''

    years= [j for j in range(init,finit+1)]
    df_articles=[] #lista dos dataframes, cada elemento traz informações sobre um mês-ano

    for year in range(len(years)):
        for month in range(1,13):
            query_url_archive = f"https://api.nytimes.com/svc/archive/v1/{years[year]}/{month}.json?api-key={your_key}"
            archive_request = requests.get(query_url_archive)     
            #d1=archive_request.json()
            #d2=pd.json_normalize(d1['response']['docs'])
            df_articles.append(archive_request)
            time.sleep(6)
    return df_articles

In [6]:
def articles_df2(archives):
    ''' retorna um dataframe com informações a respeito de artigos 
        publicados na NYT durante todo o período compreendido entre
        os anos init e finit
        
        ex. init 2020 e finit 2022, retorna dataframe de 2020, 2021 e 2022'''

    df_articles2=[] #lista dos dataframes, cada elemento traz informações sobre um mês-ano

    for i in range(35):
        #query_url_archive = f"https://api.nytimes.com/svc/archive/v1/{years[year]}/{month}.json?api-key={your_key}"
        #archive_request = requests.get(query_url_archive)     
        d1=archives[i].json()
        d2=pd.json_normalize(d1['response']['docs'])
        df_articles2.append(d2)
        print(f'{i}ok')
        
    return df_articles2

In [ ]:
def sel_columns(dataset):
    
    '''restringe as colunas de interesse para cada um dos meses da lista de datasets'''
    
    
    cleaned_columns = []
    for i in range(len(dataset)):
        dataset[i]=dataset[i][['abstract', 'web_url', 'snippet', 'lead_paragraph', 'print_section',
       'print_page', 'source', 'keywords', 'pub_date',
       'document_type', 'news_desk', 'section_name', 'type_of_material', '_id',
       'word_count', 'uri', 'headline.main', 
       'headline.print_headline', 'byline.original']]
        cleaned_columns.append(dataset[i])
    return cleaned_columns

In [10]:
df_articles=articles_df(2020,2022)

In [25]:
df_articles2=articles_df2(df_articles)
#len(df_articles2)

0ok
1ok
2ok
3ok
4ok
5ok
6ok
7ok
8ok
9ok
10ok
11ok
12ok
13ok
14ok
15ok
16ok
17ok
18ok
19ok
20ok
21ok
22ok
23ok
24ok
25ok
26ok
27ok
28ok
29ok
30ok
31ok
32ok
33ok
34ok

In [16]:
pd.set_option('display.max_columns', None) #exibir todas colunas quando chamar o dataframe

In [29]:
df_articles3=sel_columns(df_articles2)

In [31]:
df_articles3[2]

,abstract,web_url,snippet,lead_paragraph,print_section,print_page,source,keywords,pub_date,document_type,news_desk,section_name,type_of_material,_id,word_count,uri,headline.main,headline.print_headline,byline.original
0,Joseph R. Biden Jr. drew on his decades-long r...,https://www.nytimes.com/2020/02/29/us/politics...,Joseph R. Biden Jr. drew on his decades-long r...,"COLUMBIA, S.C. — Joseph R. Biden Jr. scored a ...",A,1,The New York Times,"[{'name': 'persons', 'value': 'Biden, Joseph R...",2020-03-01T00:06:07+0000,article,Politics,U.S.,News,nyt://article/c08f39a1-ec4b-5c2b-9c82-7b94a832...,1892,nyt://article/c08f39a1-ec4b-5c2b-9c82-7b94a832...,"Winning South Carolina, Biden Makes Case Again...","Vaulting to Life, Biden Captures South Carolina",By Jonathan Martin and Alexander Burns
1,President Trump appeared eager to bask in the ...,https://www.nytimes.com/2020/02/29/us/politics...,President Trump appeared eager to bask in the ...,WASHINGTON — President Trump crouched undernea...,A,29,The New York Times,"[{'name': 'subject', 'value': 'Presidential El...",2020-03-01T00:09:35+0000,article,Washington,U.S.,News,nyt://article/ea946bf4-2188-58ae-8da0-e8d86a51...,951,nyt://article/ea946bf4-2188-58ae-8da0-e8d86a51...,"At CPAC, Trump Takes Aim at Rivals",Trump Heaps Scorn on Rivals and Praise on Hims...,By Annie Karni
2,Gov. Andrew M. Cuomo announced on Saturday tha...,https://www.nytimes.com/2020/02/29/sports/hock...,Gov. Andrew M. Cuomo announced on Saturday tha...,The Islanders will be returning full-time to L...,SP,2,The New York Times,"[{'name': 'subject', 'value': 'Hockey, Ice', '...",2020-03-01T00:35:23+0000,article,Sports,Sports,News,nyt://article/340524eb-53c8-525c-86f6-134579d5...,597,nyt://article/340524eb-53c8-525c-86f6-134579d5...,The Islanders Are Saying Goodbye to Brooklyn,The Islanders Will Become Full-Time Island Res...,By Allan Kreda
3,"A person in the Seattle area has died, officia...",https://www.nytimes.com/2020/02/29/us/politics...,"A person in the Seattle area has died, officia...",WASHINGTON — Hours after officials confirmed t...,A,28,The New York Times,"[{'name': 'subject', 'value': 'Coronavirus (20...",2020-03-01T01:13:23+0000,article,Washington,U.S.,News,nyt://article/3c115172-6839-586d-a24a-9a656f09...,1670,nyt://article/3c115172-6839-586d-a24a-9a656f09...,Trump Moves to Calm Fears as First U.S. Death ...,"As U.S. Cites 1st Death From New Virus, Trump ...","By Michael Crowley, Mike Baker and Nicholas Bo..."
4,Officials filed felony hate-crime charges agai...,https://www.nytimes.com/2020/02/29/us/east-bos...,Officials filed felony hate-crime charges agai...,The mother and daughter were speaking Spanish ...,NaN,NaN,The New York Times,"[{'name': 'subject', 'value': 'Assaults', 'ran...",2020-03-01T01:38:43+0000,article,Express,U.S.,News,nyt://article/7249cd2e-11a9-5637-adfd-abaec6dd...,839,nyt://article/7249cd2e-11a9-5637-adfd-abaec6dd...,Mother and Daughter Attacked for Speaking Span...,,By Michael Levenson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4878,"Dr. Anthony S. Fauci, the nation’s leading inf...",https://www.nytimes.com/2020/03/31/us/politics...,"Dr. Anthony S. Fauci, the nation’s leading inf...",WASHINGTON — The top government scientists bat...,A,1,The New York Times,"[{'name': 'subject', 'value': 'Deaths (Fatalit...",2020-03-31T23:21:52+0000,article,Washington,U.S.,News,nyt://article/86f8eb1f-0180-57fb-bffd-763ca38f...,1659,nyt://article/86f8eb1f-0180-57fb-bffd-763ca38f...,"Coronavirus May Kill 100,000 to 240,000 in U.S...","Grim Toll Projected, Even With Distancing","By Michael D. Shear, Michael Crowley and James..."
4879,Here’s what you should and shouldn’t do.,https://www.nytimes.com/2020/03/31/style/how-t...,Here’s what you should and shouldn’t do.,Rachel Bodt has been mulling over the relevanc...,D,3,The New York Times,"[{'name': 'subject', 'value': 'Hair', 'rank': ...",2020-03-31T23:24:42+0000,article,Styles,Style,News,nyt://article/7ad6fc6d-1440-5edf-bfeb-a9a3615f...,991,nyt://article/7ad6fc6d-1440-5edf-bfeb-a9a3615f...,How to Touch Up Your Roots at Home,Touching Up Your Roots at Home,By Crystal Martin
4880,Ask yourself these questions and think about t...,https://www.nytimes.com/2020/03/31/smarter-liv...,Ask yourself these questions and think about t...,You’re scrolling Instagram when it happens: th...,NaN,NaN,The New York Times,"[{'name': 'subject', 'value': 'Pets', 'rank': ...",2020-03-31T23:30:04+0000,article,Smarter Living,Smarter Living,News,nyt://article/6723ab46-0986-59fc-bac4-2d90afac...,1751,nyt://article/6723ab46-0986-59fc-bac4-2d90afac...,Before You Adopt: Planning a Lifelong Commitme...,,By Sassafras Lowrey
4881,The mayor of Holyoke in Massachusetts confront...,https://www.nytimes.com/2020/03/31/us/coronavi...,The mayor of Holyoke in Massachusetts confront...,"NEWTON, Mass. — The mayor of Holyoke, Mass., g...",A,14,The New York Times,"[{'name': 'subject', 'value': 'Coronavirus (20...",2020-03-31T23:36:02+0000,article,National,U.S.,News,nyt://article/8964a078-c388-514f-8920-bfa15b0a...,793,nyt://article/8964a078-c388-514f-8920-bfa15b0a...,"Coronavirus Spreads in Veterans’ Home, Leaving...",Veterans’ Home in Massachusetts Faces Outbreak...,By Ellen Barry
4882,He joined the Berlin Philharmonic after years ...,https://www.nytimes.com/2020/03/31/arts/music/...,He joined the Berlin Philharmonic after years ...,"Hellmut Stern, who fled Germany with his famil...",B,12,The New York Times,"[{'name': 'persons', 'value': 'Stern, Hellmut ...",2020-03-31T23:56:30+0000,article,Obits,Arts,Obituary (Obit),nyt://article/758bc924-2da3-5b79-807e-95eca5f6...,1164,nyt://article/758bc924-2da3-5b79-807e-95eca5f6...,"Hellmut Stern, 91, Dies; Violinist Returned to...","Hellmut Stern, 91, Violinist; Shone in Berlin ...",By Katharine Q. Seelye

In [39]:
def concat_df (dataset_list):
    '''concatenar datasets presentes em uma lista '''
    limit=len(dataset_list)
    i=1
    while i<= limit:
        dataset_list[i]=pd.concat([dataset_list[i-1], dataset_list[i]], ignore_index=True) 
        i+=1
    df=dataset_list[limit]
    return df

In [40]:
df_union=concat_df(df_articles3)

KeyboardInterrupt:

In [38]:
len(df_articles3)

35

In [44]:
a=list(range(20,720,20))

In [51]:

soma=0
for var in range(20, 700, 20):
    print(var)
    soma = soma + var
print (soma)

20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
500
520
540
560
580
600
620
640
660
680
11900